# ----
# Site

title: Base
url: ""
baseurl: "/nghich"
google_analytics_key:
disqus_shortname:
newsletter_action:

# -----
# Build

permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"
